import { UserProfile } from './types';

export const mockProfiles: UserProfile[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    role: 'Full-Stack Developer',
    location: 'San Francisco, CA',
    bio: 'Building products that matter. 8 years of experience in React, Node, and cloud infrastructure. Looking for my next big challenge.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    availability: 'available',
    openTo: ['freelance', 'equity', 'cofounding'],
    skills: ['React', 'Node.js', 'AWS', 'TypeScript', 'PostgreSQL'],
    contactEmail: 'sarah@example.com',
    twitter: 'sarahchen',
    calendarLink: 'https://cal.com/sarahchen',
    portfolioLinks: ['https://sarahchen.dev'],
    tier: 'pro',
    featured: true,
    profileViews: 1247,
    contactClicks: 89,
    createdAt: '2024-01-15',
    lastActive: '2024-01-28',
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    role: 'Product Designer',
    location: 'New York, NY',
    bio: 'Design leader with a passion for creating delightful user experiences. Previously at Stripe and Airbnb.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    availability: 'open',
    openTo: ['advising', 'sideprojects'],
    skills: ['Figma', 'User Research', 'Design Systems'],
    contactEmail: 'marcus@example.com',
    twitter: 'marcusjohnson',
    portfolioLinks: ['https://marcus.design'],
    tier: 'pro',
    featured: true,
    profileViews: 892,
    contactClicks: 67,
    createdAt: '2024-01-10',
    lastActive: '2024-01-27',
  },
  {
    id: '3',
    name: 'Elena Rodriguez',
    email: 'elena@example.com',
    role: 'Startup Founder & Advisor',
    location: 'Austin, TX',
    bio: 'Serial entrepreneur. Built and sold 2 companies. Now helping the next generation of founders.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    availability: 'available',
    openTo: ['advising', 'cofounding', 'equity'],
    skills: ['Strategy', 'Fundraising', 'Go-to-Market', 'Team Building'],
    contactEmail: 'elena@example.com',
    telegram: 'elenarodriguez',
    calendarLink: 'https://calendly.com/elena',
    portfolioLinks: [],
    tier: 'premium',
    featured: true,
    profileViews: 2341,
    contactClicks: 156,
    createdAt: '2024-01-05',
    lastActive: '2024-01-28',
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david@example.com',
    role: 'Machine Learning Engineer',
    location: 'Seattle, WA',
    bio: 'AI/ML specialist focused on NLP and computer vision. Looking for interesting problems to solve.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    availability: 'available',
    openTo: ['freelance', 'fulltime', 'equity'],
    skills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps'],
    contactEmail: 'david@example.com',
    twitter: 'davidkim_ml',
    portfolioLinks: ['https://github.com/davidkim'],
    tier: 'pro',
    featured: false,
    profileViews: 567,
    contactClicks: 34,
    createdAt: '2024-01-18',
    lastActive: '2024-01-26',
  },
  {
    id: '5',
    name: 'Aisha Patel',
    email: 'aisha@example.com',
    role: 'Growth Marketer',
    location: 'London, UK',
    bio: 'Data-driven marketer with expertise in B2B SaaS. Helped 5 startups reach $1M ARR.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    availability: 'open',
    openTo: ['freelance', 'advising'],
    skills: ['SEO', 'Content Marketing', 'Analytics'],
    contactEmail: 'aisha@example.com',
    twitter: 'aishapatel',
    portfolioLinks: [],
    tier: 'free',
    featured: false,
    profileViews: 234,
    contactClicks: 12,
    createdAt: '2024-01-20',
    lastActive: '2024-01-25',
  },
  {
    id: '6',
    name: 'James Wilson',
    email: 'james@example.com',
    role: 'Backend Engineer',
    location: 'Toronto, Canada',
    bio: 'Building scalable systems. Rust enthusiast. Open to challenging backend projects.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    availability: 'available',
    openTo: ['freelance', 'sideprojects'],
    skills: ['Rust', 'Go', 'Kubernetes'],
    contactEmail: 'james@example.com',
    twitter: 'jameswilson',
    portfolioLinks: ['https://jameswilson.io'],
    tier: 'pro',
    featured: false,
    profileViews: 445,
    contactClicks: 28,
    createdAt: '2024-01-12',
    lastActive: '2024-01-28',
  },
  {
    id: '7',
    name: 'Lisa Thompson',
    email: 'lisa@example.com',
    role: 'UX Researcher',
    location: 'Berlin, Germany',
    bio: 'Understanding users is my superpower. Qualitative and quantitative research expert.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    availability: 'available',
    openTo: ['freelance', 'fulltime'],
    skills: ['User Research', 'Usability Testing', 'Data Analysis'],
    contactEmail: 'lisa@example.com',
    calendarLink: 'https://cal.com/lisathompson',
    portfolioLinks: [],
    tier: 'free',
    featured: false,
    profileViews: 189,
    contactClicks: 8,
    createdAt: '2024-01-22',
    lastActive: '2024-01-24',
  },
  {
    id: '8',
    name: 'Michael Brown',
    email: 'michael@example.com',
    role: 'Investor & Angel',
    location: 'Miami, FL',
    bio: 'Early stage investor focused on fintech and healthtech. Writing checks from $25k to $250k.',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face',
    availability: 'open',
    openTo: ['advising', 'equity'],
    skills: ['Due Diligence', 'Financial Modeling', 'Network'],
    contactEmail: 'michael@example.com',
    twitter: 'michaelbrown_vc',
    telegram: 'michaelbrown',
    portfolioLinks: ['https://michaelbrown.vc'],
    tier: 'premium',
    featured: true,
    profileViews: 3456,
    contactClicks: 234,
    createdAt: '2024-01-03',
    lastActive: '2024-01-28',
  },
  {
    id: '9',
    name: 'Nina Kowalski',
    email: 'nina@example.com',
    role: 'Mobile Developer',
    location: 'Warsaw, Poland',
    bio: 'iOS and Android developer with 6 years of experience. Flutter enthusiast.',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
    availability: 'available',
    openTo: ['freelance', 'cofounding', 'sideprojects'],
    skills: ['Swift', 'Kotlin', 'Flutter'],
    contactEmail: 'nina@example.com',
    twitter: 'ninakowalski',
    portfolioLinks: [],
    tier: 'pro',
    featured: false,
    profileViews: 678,
    contactClicks: 45,
    createdAt: '2024-01-14',
    lastActive: '2024-01-27',
  },
];

export const currentUser: UserProfile = {
  id: 'current',
  name: 'Alex Morgan',
  email: 'alex@example.com',
  role: 'Software Engineer',
  location: 'Portland, OR',
  bio: 'Passionate about building great products. Currently exploring new opportunities.',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop&crop=face',
  availability: 'available',
  openTo: ['freelance', 'cofounding'],
  skills: ['JavaScript'],
  contactEmail: 'alex@example.com',
  twitter: 'alexmorgan',
  portfolioLinks: [],
  tier: 'free',
  featured: false,
  profileViews: 42,
  contactClicks: 3,
  createdAt: '2024-01-25',
  lastActive: '2024-01-28',
};
